version: "3.3"

services:
  matrix-synapse:
    container_name: matrix-synapse
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    volumes:
      - ./matrix-synapse-files:/data
    depends_on:
      - matrix-synapse-db
    ports:
      - 8448:8448/tcp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.synapse.rule=Host(`synapse.${DOMAIN}`)"
      - "traefik.http.routers.synapse.entrypoints=websecure"
      - "traefik.http.routers.synapse.tls.certresolver=mytlschallenge"
      - "traefik.http.services.synapse.loadbalancer.server.port=8008"
    networks:
      - proxy

  matrix-synapse-nginx:
    container_name: "matrix-synapse-nginx"
    image: nginx:latest
    restart: always
    volumes:
      - ./matrix-synapse-nginx/matrix.conf:/etc/nginx/conf.d/default.conf
      - ./matrix-synapse-nginx/www:/var/www/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`matrix.${DOMAIN}`)"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.tls.certresolver=mytlschallenge"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
    networks:
      - proxy

  matrix-synapse-db:
    container_name: matrix-synapse-db
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./matrix-synapse-schemas:/var/lib/postgresql/data
    networks:
      - proxy

networks:
  proxy:
    external: true
